server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: cos
    password: cos1234

  jpa:
    open-in-view: true
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
=======
#      ddl-auto: create
      ddl-auto: update
>>>>>>> 88d6f3f49ca889443c0a6599b70fe0febc34de8f
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    '[example.ex1.demo]': DEBUG

